version: '2.0'
services:
  mysql:
    image: mysql:8.0.20
    command: --lower_case_table_names=1 --max_allowed_packet=32M
    ports:
      - "3308:3308"
    volumes:
      - ./data:/var/lib/mysql
      - ./etc:/etc/mysql/mysql.conf.d:rw,cached
      - ./log:/var/log
    env_file:
      - ./env/mysql.env
    restart: on-failure

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - "mysql"
    restart: always

  namedida-api:
    image: namedidaapi:latest
    volumes:
      - ./namedida/data:/data
    env_file:
      - env/namedida-api.env
    restart: always
    depends_on:
      - "mysql"
